[settings]
node_spawn_timeout = 240

[relaychain]
default_command = "{{POLKADOT_BINARY_PATH}}"
default_args = [ "-lparachain=debug,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace,xcm::should_execute=trace" ]
chain = "wococo-local"

	[[relaychain.nodes]]
	name = "alice-validator-wo"
	validator = true
	rpc_port = 9935
	ws_port = 9945
	extra_args = ["--no-mdns"]

	[[relaychain.nodes]]
	name = "bob-validator-wo"
	validator = true
	rpc_port = 9936
	ws_port = 9946
	extra_args = ["--no-mdns --bootnodes {{'alice-validator-wo'|zombie('multiAddress')}}"]

	[[relaychain.nodes]]
	name = "charlie-validator-wo"
	validator = true
	rpc_port = 9937
	ws_port = 9947
	extra_args = ["--no-mdns --bootnodes {{'alice-validator-wo'|zombie('multiAddress')}}"]

[[parachains]]
id = 1014
chain = "bridge-hub-wococo-local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice-collator-wo"
	validator = true
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
	rpc_port = 8935
	ws_port = 8945
	args = [
		"-lparachain=debug,runtime::mmr=info,substrate=info,runtime=info,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace,xcm::should_execute=trace",
	]

	# run bob as parachain collator
	[[parachains.collators]]
	name = "bob-collator-wo"
	validator = true
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
	rpc_port = 8936
	ws_port = 8946
	args = [
		"-lparachain=trace,runtime::mmr=info,substrate=info,runtime=info,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace,xcm::should_execute=trace",
	]

[[parachains]]
id = 1000
chain = "westmint-local"
cumulus_based = true

	[[parachains.collators]]
	name = "wockmint-collator1"
	rpc_port = 9011
	ws_port = 9010
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH_FOR_WOCKMINT}}"
	args = [
		"-lparachain=debug,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace,xcm::should_execute=trace",
	]

	[[parachains.collators]]
	name = "wockmint-collator2"
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH_FOR_WOCKMINT}}"
	args = [
		"-lparachain=debug,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace,xcm::should_execute=trace",
	]

[[hrmp_channels]]
sender = 1000
recipient = 1014
max_capacity = 4
max_message_size = 524288

[[hrmp_channels]]
sender = 1014
recipient = 1000
max_capacity = 4
max_message_size = 524288
